name = "gooderly-website"
pages_build_output_dir = "."
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[send_email]]
name = "CONTACT_EMAIL"
destination_address = "a16389787@yahoo.com.tw"
